version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgreswallet
      POSTGRES_PASSWORD: postgreswallet
      POSTGRES_DB: wallet
    networks:
      - wallet
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgreswallet
      POSTGRES_PASSWORD: postgreswallet
      POSTGRES_DB: wallet
    networks:
      - wallet
networks:
  wallet: